Reorganization in support of preparing for mono-repo
twosixlabs/armory-library pull request #40
Opened 2023-11-06 13:50 UTC by treubig26

Moves the armory-library source into the `library` sub-folder. Additionally, the `charmory_examples` package is renamed to `armory/examples` where `armory` becomes a [namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/).

2023-11-06 20:40 UTC, mwartell commented on requirements.txt
> +#
This requirements.txt has got to go: it is semantically overloaded

```
$ cat install.sh
#!/bin/bash
echo "installing all armory-suite components with pip"
set -x -e
pip install .
pip install library
pip install examples[all]
```

2023-11-06 20:42 UTC, mwartell commented on .github/workflows/ci.yml
> +          pip3 install --no-compile --editable .
There is extreme overuse of editable in Armory (new and old) materials. Most people aren't developing Armory so we should never provide `--editable` without really good cause.

In CI, `--editable` is non-sensical unless you are testing editable

2023-11-06 20:44 UTC, mwartell commented on pyproject.toml
> +[tool.taskipy.tasks]
I like taskipy, so fresh, so clean.

2023-11-06 20:47 UTC, mwartell requested changes
Sample replacement code for requirements.txt included.

2023-11-06 20:47 UTC, mwartell requested changes
Sample replacement code for requirements.txt included.

2023-11-07 17:44 UTC, treubig26 commented on dev-install.sh
> +fi
I'm not sure I follow. Are you suggesting something different than the echo on line 22?

2023-11-07 18:25 UTC, merged